

export const TIMEOUTS = {
    TOGGLE_VERIFY_USEC: 300000,
    TOGGLE_EXTRA_USEC: 200000,
    LOCK_RETRY_USEC: 200000,

    LOCK_UPDATE_INTERVAL_MS: 10000,
    COMMAND_POLL_INTERVAL_MS: 100,
    INITIALIZATION_DELAY_MS: 1000,

    LOCK_MAX_AGE_SEC: 30,
    RECENT_RELOAD_THRESHOLD_SEC: 30,

    TOGGLE_COOLDOWN_MS: 300,
    ANIMATION_FRAME_MS: 16,

    CURL_HEAD_TIMEOUT_SEC: 8,
    DOWNLOAD_TOTAL_TIMEOUT_SEC: 300,

    UI_IMMEDIATE_MS: 0,
    UI_BATCH_TINY_MS: 5,
    UI_BATCH_SMALL_MS: 10,
    UI_REFRESH_QUICK_MS: 50,
    UI_REFRESH_MS: 100,
    PULSE_INTERVAL_MS: 120,
    UI_DELAY_SHORT_MS: 150,
    PROGRESS_POLL_MS: 200,
    TAB_SWITCH_DELAY_MS: 300,
    DEBOUNCE_MS: 500,

    FEEDBACK_SHORT_MS: 1000,
    FALLBACK_TIMEOUT_MS: 1500,
    FEEDBACK_LONG_MS: 2000,
    ERROR_DISPLAY_MS: 3000,

    NETWORK_TIMEOUT_MS: 10000
};


export const ANIMATION = {
    SNAKE_SPEED: 0.015,
    SNAKE_LENGTH: 0.15,
    BORDER_RADIUS: 12,
    LINE_WIDTH: 3,
    GLOW_SEGMENTS: 15,
    DRAW_SEGMENTS: 20
};


export const UI_SIZES = {
    PROGRESS_BAR_WIDTH: 120,
    PROGRESS_BAR_HEIGHT: 6,
    SPINNER_SIZE: 20,
    DEFAULT_SPACING: 8,
    SMALL_SPACING: 4,
    DEFAULT_MARGIN: 8,
    LARGE_MARGIN: 12
};
